/**
 * Builds markdown from the results history:
 *  - REPORT.md — the newest run per (scenario, grid, size), with provenance
 *  - HISTORY.md — central chronological log of every recorded bench run
 * Metric definitions and caveats: docs/benchmarking.md.
 *
 * Usage: pnpm bench:report            # print REPORT to stdout
 *        pnpm bench:report --write    # also update results/REPORT.md + results/HISTORY.md
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const RESULTS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'results');

interface Meta {
	date: string;
	versions?: Record<string, string>;
	commit: string;
	dirty: boolean;
	browser: string;
	cpu: string;
	cores: number;
}

interface Run {
	scenario: string;
	grid: string;
	size: string;
	exec?: 'main' | 'worker' | 'hybrid';
	theme?: 'graphite' | 'tailwind';
	gridVersion?: string;
	repeats: number;
	medians: Record<string, number>;
}

interface ResultsFile {
	name: string;
	meta: Meta;
	results: Run[];
}

const files: ResultsFile[] = readdirSync(RESULTS_DIR)
	.filter((f) => f.endsWith('.json'))
	.sort() // timestamped names → chronological
	.map((name) => ({ name, ...(JSON.parse(readFileSync(join(RESULTS_DIR, name), 'utf8')) as Omit<ResultsFile, 'name'>) }));

if (files.length === 0) {
	console.error('No results files found. Run `pnpm bench` first.');
	process.exit(1);
}

const gridLabel = (run: Run): string =>
	`${run.grid}${run.exec && run.exec !== 'main' ? ` (${run.exec})` : ''}${run.theme && run.theme !== 'graphite' ? ` [${run.theme}]` : ''}${run.gridVersion ? ` ${run.gridVersion}` : ''}`;

// --- REPORT.md: later files overwrite earlier ones per key ---

const latest = new Map<string, { run: Run; meta: Meta; file: string }>();
for (const file of files) {
	for (const run of file.results) {
		latest.set(`${run.scenario}|${run.grid}|${run.exec ?? 'main'}|${run.theme ?? 'graphite'}|${run.size}`, {
			run,
			meta: file.meta,
			file: file.name
		});
	}
}

const report: string[] = [];
report.push('# Benchmark report');
report.push('');
report.push('Newest recorded run per scenario/grid/size. Regenerate with `pnpm bench:report --write`.');
report.push('Metric definitions and caveats: [docs/benchmarking.md](../../docs/benchmarking.md). Full log: [HISTORY.md](HISTORY.md).');
report.push('');

for (const { run, meta, file } of [...latest.values()].sort(
	(a, b) => a.run.scenario.localeCompare(b.run.scenario) || a.run.grid.localeCompare(b.run.grid)
)) {
	report.push(`## ${run.scenario} — ${gridLabel(run)}, ${run.size} rows (median of ${run.repeats})`);
	report.push('');
	const core = meta.versions?.['@speedytables/core'];
	report.push(
		`_${meta.date} · ${core ? `core v${core} · ` : ''}commit ${meta.commit}${meta.dirty ? ' (dirty)' : ''} · ${meta.cpu.trim()} (${meta.cores} cores) · Chromium ${meta.browser} · [${file}](${file})_`
	);
	report.push('');
	report.push('| metric | value |');
	report.push('| --- | ---: |');
	for (const [key, value] of Object.entries(run.medians)) {
		report.push(`| ${key} | ${value} |`);
	}
	report.push('');
}

// --- HISTORY.md: one row per recorded file ---

const history: string[] = [];
history.push('# Benchmark history');
history.push('');
history.push('Every recorded bench run, chronologically. Generated by `pnpm bench:report --write`.');
history.push('');
history.push('| date (UTC) | core | grid under test | commit | scenarios | file |');
history.push('| --- | --- | --- | --- | --- | --- |');
for (const file of files) {
	const grids = [...new Set(file.results.map(gridLabel))].join(', ');
	const scenarios = [...new Set(file.results.map((r) => `${r.scenario}@${r.size}`))].join(', ');
	const core = file.meta.versions?.['@speedytables/core'] ?? '—';
	history.push(
		`| ${file.meta.date.slice(0, 16).replace('T', ' ')} | ${core} | ${grids} | ${file.meta.commit}${file.meta.dirty ? ' (dirty)' : ''} | ${scenarios} | [${file.name}](${file.name}) |`
	);
}
history.push('');

console.log(report.join('\n'));

if (process.argv.includes('--write')) {
	writeFileSync(join(RESULTS_DIR, 'REPORT.md'), report.join('\n') + '\n');
	writeFileSync(join(RESULTS_DIR, 'HISTORY.md'), history.join('\n') + '\n');
	console.error(`\nWrote REPORT.md and HISTORY.md in ${RESULTS_DIR}`);
}
